### ISSUE TITLE
Tutoriale Ziemka

### ISSUE THREAD

**Issue by DawidBydlosz** [HEXproject/Assets-Cscripts#16]
1; Game objecty, oraz .Transform, Parent i Child
2: Jak przesunąć np szescian ze zwyklym krokiem, a jak np przyspieszający
3: Instantiate

**Comment by DawidBydlosz** [comment]
+Skalowanie,
+Wykorzystywanie funkcji z jednego skryptu w drugim itp, przekazywanie wartosci miedzy skryptami (bez public)

**Comment by AeTher97** [comment]
To się chyba już nie przyda
